version: '3.9'

services:
  frontend:
    container_name: frontend
    image: frontend:frontend
    build:
      context: ./client
      dockerfile: frontend.dockerfile
    ports:
      - 3001:3001
    environment:
      - NEXT_PUBLIC_API_URL=http://http://localhost/:3001
    restart: always
    depends_on:
      - backend
  backend:
    container_name: backend
    image: backend:backend
    build:
      context: ./server
      dockerfile: backend.dockerfile
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/PetHome
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      # - ./.database/postgres/data:/var/lib/postgresql/data
      - /postgres/data:/var/lib/postgresql/data
      # - /postgres/pgdata:/var/lib/postgresql/data postgres
