import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/src/widgets/nav-bar/NavBar'
import { SITE_NAME } from '@/constants/seo.constants'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: {
		default: SITE_NAME,
		template: `%s | ${SITE_NAME}`,
	},
	description: 'Generated by create next app',
}

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Providers>
					<NavBar />
					{children}
				</Providers>
			</body>
		</html>
	)
}
